_target_: src.dataset.rgbt_dataset
barch_size: ${batch_size}
topo: True
data_path: 'data/matteo21/jpg'
train_root: 'train'
val_root: 'valid'
test_root: 'test'
in_channels: 4
out_channels: 1
shape: 256